name: ci

on:
  push:
    branches:
      - main
      - citus_test
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'
  pull_request:
    branches:
      - main
      - citus_test
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'

jobs:
  citus:
    name: DBMS Tests (Citus)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build SQLancer
        run: mvn -B package -DskipTests=true
      - name: Set up Citus
        run: |
          # echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee  /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          curl https://install.citusdata.com/community/deb.sh | sudo bash
          sudo apt-get -y install  postgresql-17-citus-13.0
          sudo chown -R $USER:$USER /var/run/postgresql
          export PATH=/usr/lib/postgresql/17/bin:$PATH
          cd ~
          mkdir -p citus/coordinator citus/worker1 citus/worker2
          initdb -D citus/coordinator
          initdb -D citus/worker1
          initdb -D citus/worker2
          echo "shared_preload_libraries = 'citus'" >> citus/coordinator/postgresql.conf
          echo "shared_preload_libraries = 'citus'" >> citus/worker1/postgresql.conf
          echo "shared_preload_libraries = 'citus'" >> citus/worker2/postgresql.conf
          pg_ctl -D citus/coordinator -o "-p 9700" -l coordinator_logfile start || cat coordinator_logfile || cat citus/coordinator/coordinator_logfile
          pg_ctl -D citus/worker1 -o "-p 9701" -l worker1_logfile start
          ls citus/worker1
          pg_ctl -D citus/worker2 -o "-p 9702" -l worker2_logfile start
          psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -p 9700 -d postgres -U $USER
          createdb test -p 9700 -U $USER
          psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -p 9701 -d postgres -U $USER
          createdb test -p 9701 -U $USER
          psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -p 9702 -d postgres -U $USER
          createdb test -p 9702 -U $USER
          psql -c "CREATE EXTENSION citus;" -p 9700 -U $USER -d test
          psql -c "CREATE EXTENSION citus;" -p 9701 -U $USER -d test
          psql -c "CREATE EXTENSION citus;" -p 9702 -U $USER -d test
          psql -c "SELECT * from citus_add_node('localhost', 9701);" -p 9700 -U $USER -d test
          psql -c "SELECT * from citus_add_node('localhost', 9702);" -p 9700 -U $USER -d test
      - name: Run Tests
        run: CITUS_AVAILABLE=true mvn -Dtest=TestCitus test
